/** @type {import('tailwindcss').Config} */
// Tokens portados 1:1 desde UI/UI.html (design system Material 3).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#3f465c',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#00174b',
        error: '#ba1a1a',
        'on-primary-fixed': '#131b2e',
        'on-tertiary-container': '#98805d',
        'secondary-container': '#316bf3',
        'inverse-on-surface': '#f3f0f2',
        'on-secondary-container': '#fefcff',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary': '#ffffff',
        secondary: '#0051d5',
        surface: '#fcf8fa',
        'surface-container-low': '#f6f3f5',
        'surface-container': '#f0edef',
        'outline-variant': '#c6c6cd',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        background: '#fcf8fa',
        'tertiary-fixed-dim': '#dec29a',
        'tertiary-container': '#271901',
        'inverse-surface': '#303032',
        'primary-container': '#131b2e',
        'on-secondary-fixed-variant': '#003ea8',
        'surface-bright': '#fcf8fa',
        'on-surface': '#1b1b1d',
        'primary-fixed': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        outline: '#76777d',
        'tertiary-fixed': '#fcdeb5',
        'surface-tint': '#565e74',
        'surface-container-highest': '#e4e2e4',
        primary: '#000000',
        'on-tertiary-fixed-variant': '#574425',
        'surface-variant': '#e4e2e4',
        'on-error-container': '#93000a',
        'on-primary-container': '#7c839b',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcd9db',
        'on-surface-variant': '#45464d',
        'inverse-primary': '#bec6e0',
        'surface-container-high': '#eae7e9',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#271901',
        tertiary: '#000000',
        'on-background': '#1b1b1d',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-collapsed': '64px',
        xl: '32px',
        lg: '24px',
        gutter: '20px',
        md: '16px',
        'sidebar-width': '260px',
        sm: '8px',
        xs: '4px',
        unit: '4px',
        'container-max': '1440px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'code-sm': ['Roboto Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
